using FluentAssertions;
using EngQuest.Domain.Shared;
using EngQuest.Domain.Vocabulary.ComparisonAdjectives;

namespace EngQuest.Domain.UnitTests.Vocabulary.ComparisonAdjectives;

public class SuperlativeFormTests
{
    [Fact]
    public void Is_Should_ReturnTrue_IfAdjectiveStarsWithMost()
    {
        // Arrange
        var superlativeForm = new Text("most dangerous");
        
        // Act
        bool result = SuperlativeForm.Is(superlativeForm);

        // Assert
        result.Should().BeTrue();
    }
    
    [Fact]
    public void Is_Should_ReturnTrue_IfAdjectiveEndsWithEr()
    {
        // Arrange
        var superlativeForm = new Text("lowest");
        
        // Act
        bool result = SuperlativeForm.Is(superlativeForm);

        // Assert
        result.Should().BeTrue();
    }

    [Theory]
    [InlineData("nice", "nicest", 1)]
    [InlineData("new", "newest", 1)]
    [InlineData("plain", "plainest", 1)]
    [InlineData("odd", "oddest", 1)]
    [InlineData("neat", "neatest", 1)]
    [InlineData("mild", "mildest", 1)]
    [InlineData("mean", "meanest", 1)]
    [InlineData("near", "nearest", 1)]
    [InlineData("moist", "moistest", 1)]
    [InlineData("raw", "rawest", 1)]
    [InlineData("rare", "rarest", 1)]
    [InlineData("ripe", "ripest", 1)]
    [InlineData("rich", "richest", 1)]
    [InlineData("quiet", "quietest", 1)]
    [InlineData("proud", "proudest", 1)]
    [InlineData("poor", "poorest", 1)]
    [InlineData("quick", "quickest", 1)]
    [InlineData("pure", "purest", 1)]
    [InlineData("mad", "maddest", 1)]
    [InlineData("harsh", "harshest", 1)]
    [InlineData("hard", "hardest", 1)]
    [InlineData("hip", "hippest", 1)]
    [InlineData("high", "highest", 1)]
    [InlineData("gross", "grossest", 1)]
    [InlineData("grand", "grandest", 1)]
    [InlineData("gentle", "gentlest", 1)]
    [InlineData("great", "greatest", 1)]
    [InlineData("grave", "gravest", 1)]
    [InlineData("little", "littlest", 1)]
    [InlineData("light", "lightest", 1)]
    [InlineData("low", "lowest", 1)]
    [InlineData("loud", "loudest", 1)]
    [InlineData("late", "latest", 1)]
    [InlineData("humble", "humblest", 1)]
    [InlineData("hot", "hottest", 1)]
    [InlineData("kind", "kindest", 1)]
    [InlineData("large", "largest", 1)]
    [InlineData("tough", "toughest", 1)]
    [InlineData("thick", "thickest", 1)]
    [InlineData("warm", "warmest", 1)]
    [InlineData("true", "truest", 1)]
    [InlineData("tan", "tannest", 1)]
    [InlineData("strict", "strictest", 1)]
    [InlineData("strange", "strangest", 1)]
    [InlineData("sweet", "sweetest", 1)]
    [InlineData("strong", "strongest", 1)]
    [InlineData("long", "longest", 1)]
    [InlineData("young", "youngest", 1)]
    [InlineData("tall", "tallest", 1)]
    [InlineData("old", "oldest", 1)]
    [InlineData("wild", "wildest", 1)]
    [InlineData("weird", "weirdest", 1)]
    [InlineData("weak", "weakest", 1)]
    [InlineData("wide", "widest", 1)]
    [InlineData("wet", "wettest", 1)]
    [InlineData("steep", "steepest", 1)]
    [InlineData("short", "shortest", 1)]
    [InlineData("sharp", "sharpest", 1)]
    [InlineData("simple", "simplest", 1)]
    [InlineData("shy", "shyest", 1)]
    [InlineData("sane", "sanest", 1)]
    [InlineData("rude", "rudest", 1)]
    [InlineData("rough", "roughest", 1)]
    [InlineData("safe", "safest", 1)]
    [InlineData("sad", "saddest", 1)]
    [InlineData("soon", "soonest", 1)]
    [InlineData("soft", "softest", 1)]
    [InlineData("sour", "sourest", 1)]
    [InlineData("sore", "sorest", 1)]
    [InlineData("smooth", "smoothest", 1)]
    [InlineData("slow", "slowest", 1)]
    [InlineData("slim", "slimmest", 1)]
    [InlineData("smart", "smartest", 1)]
    [InlineData("small", "smallest", 1)]
    [InlineData("bold", "boldest", 1)]
    [InlineData("dry", "dryest", 1)]
    [InlineData("blue", "bluest", 1)]
    [InlineData("brave", "bravest", 1)]
    [InlineData("deep", "deepest", 1)]
    [InlineData("dense", "densest", 1)]
    [InlineData("black", "blackest", 1)]
    [InlineData("faint", "faintest", 1)]
    [InlineData("fair", "fairest", 1)]
    [InlineData("dull", "dullest", 1)]
    [InlineData("dumb", "dumbest", 1)]
    [InlineData("bland", "blandest", 1)]
    [InlineData("brief", "briefest", 1)]
    [InlineData("clear", "clearest", 1)]
    [InlineData("clean", "cleanest", 1)]
    [InlineData("cheap", "cheapest", 1)]
    [InlineData("close", "closest", 1)]
    [InlineData("coarse", "coarsest", 1)]
    [InlineData("cold", "coldest", 1)]
    [InlineData("damp", "dampest", 1)]
    [InlineData("bright", "brightest", 1)]
    [InlineData("dark", "darkest", 1)]
    [InlineData("calm", "calmest", 1)]
    [InlineData("broad", "broadest", 1)]
    [InlineData("cute", "cutest", 1)]
    [InlineData("fat", "fattest", 1)]
    [InlineData("few", "fewest", 1)]
    [InlineData("full", "fullest", 1)]
    [InlineData("big", "biggest", 1)]
    [InlineData("thin", "thinnest", 1)]
    [InlineData("fresh", "freshest", 1)]
    [InlineData("fierce", "fiercest", 1)]
    [InlineData("firm", "firmest", 1)]
    [InlineData("fine", "finest", 1)]
    [InlineData("fit", "fittest", 1)]
    [InlineData("fast", "fastest", 1)]
    [InlineData("cool", "coolest", 1)]
    [InlineData("flat", "flattest", 1)]
    [InlineData("wise", "wisest", 1)]
    [InlineData("busy", "busiest", 2)]
    [InlineData("chewy", "chewiest", 2)]
    [InlineData("sorry", "sorriest", 2)]
    [InlineData("angry", "angriest", 2)]
    [InlineData("happy", "happiest", 2)]
    [InlineData("sincere", "most sincere", 2)]
    [InlineData("skinny", "skinniest", 2)]
    [InlineData("clever", "cleverest", 2)]
    [InlineData("windy", "windiest", 2)]
    [InlineData("silly", "silliest", 2)]
    [InlineData("sleepy", "sleepiest", 2)]
    [InlineData("smelly", "smelliest", 2)]
    [InlineData("smoky", "smokiest", 2)]
    [InlineData("chubby", "chubbiest", 2)]
    [InlineData("slimy", "slimiest", 2)]
    [InlineData("classy", "classiest", 2)]
    [InlineData("tired", "most tired", 2)]
    [InlineData("worthy", "worthiest", 2)]
    [InlineData("tiny", "tiniest", 2)]
    [InlineData("peaceful", "most peaceful", 2)]
    [InlineData("thirsty", "thirstiest", 2)]
    [InlineData("ugly", "ugliest", 2)]
    [InlineData("careful", "most careful", 2)]
    [InlineData("pleasant", "most pleasant", 2)]
    [InlineData("worldly", "worldliest", 2)]
    [InlineData("wealthy", "wealthiest", 2)]
    [InlineData("thoughtful", "most thoughtful", 2)]
    [InlineData("tasty", "tastiest", 2)]
    [InlineData("humble", "humblest", 2)]
    [InlineData("simple", "simplest", 2)]
    [InlineData("stingy", "stingiest", 2)]
    [InlineData("spicy", "spiciest", 2)]
    [InlineData("gentle", "gentlest", 2)]
    [InlineData("bossy", "bossiest", 2)]
    [InlineData("bloody", "bloodiest", 2)]
    [InlineData("bitter", "bitterest", 2)]
    [InlineData("narrow", "narrowest", 2)]
    [InlineData("sunny", "sunniest", 2)]
    [InlineData("sweaty", "sweatiest", 2)]
    [InlineData("likely", "likeliest", 2)]
    [InlineData("lively", "liveliest", 2)]
    [InlineData("lonely", "loneliest", 2)]
    [InlineData("juicy", "juiciest", 2)]
    [InlineData("fancy", "fanciest", 2)]
    [InlineData("lazy", "laziest", 2)]
    [InlineData("lovely", "loveliest", 2)]
    [InlineData("messy", "messiest", 2)]
    [InlineData("modern", "most modern", 2)]
    [InlineData("nasty", "nastiest", 2)]
    [InlineData("easy", "easiest", 2)]
    [InlineData("early", "earliest", 2)]
    [InlineData("dusty", "dustiest", 2)]
    [InlineData("itchy", "itchiest", 2)]
    [InlineData("greedy", "greediest", 2)]
    [InlineData("guilty", "guiltiest", 2)]
    [InlineData("hairy", "hairiest", 2)]
    [InlineData("gloomy", "gloomiest", 2)]
    [InlineData("friendly", "friendliest", 2)]
    [InlineData("greasy", "greasiest", 2)]
    [InlineData("handy", "handiest", 2)]
    [InlineData("filthy", "filthiest", 2)]
    [InlineData("hungry", "hungriest", 2)]
    [InlineData("icy", "iciest", 2)]
    [InlineData("flaky", "flakiest", 2)]
    [InlineData("healthy", "healthiest", 2)]
    [InlineData("heavy", "heaviest", 2)]
    [InlineData("naughty", "naughtiest", 2)]
    [InlineData("roomy", "roomiest", 2)]
    [InlineData("risky", "riskiest", 2)]
    [InlineData("crazy", "craziest", 2)]
    [InlineData("creamy", "creamiest", 2)]
    [InlineData("cruel", "most cruel", 2)]
    [InlineData("crunchy", "crunchiest", 2)]
    [InlineData("creepy", "creepiest", 2)]
    [InlineData("crispy", "crispiest", 2)]
    [InlineData("clumsy", "clumsiest", 2)]
    [InlineData("shallow", "shallowest", 2)]
    [InlineData("cloudy", "cloudiest", 2)]
    [InlineData("shiny", "shiniest", 2)]
    [InlineData("funny", "funniest", 2)]
    [InlineData("rusty", "rustiest", 2)]
    [InlineData("scary", "scariest", 2)]
    [InlineData("salty", "saltiest", 2)]
    [InlineData("polite", "politest", 2)]
    [InlineData("needy", "neediest", 2)]
    [InlineData("dirty", "dirtiest", 2)]
    [InlineData("noisy", "noisiest", 2)]
    [InlineData("oily", "oiliest", 2)]
    [InlineData("deadly", "deadliest", 2)]
    [InlineData("curvy", "curviest", 2)]
    [InlineData("pretty", "prettiest", 2)]
    [InlineData("curly", "curliest", 2)]
    [InlineData("difficult", "most difficult", 3)]
    [InlineData("expensive", "most expensive", 3)]
    [InlineData("important", "most important", 3)]
    [InlineData("generous", "most generous", 3)]
    [InlineData("popular", "most popular", 3)]
    [InlineData("intelligent", "most intelligent", 4)]
    [InlineData("interesting", "most interesting", 4)]
    [InlineData("beautiful", "most beautiful", 5)]
    public void From_Should_ReturnCorrectSuperlativeForm(string oneSyllableAdjective, string correct, int syllablesCount)
    {
        // Arrange
        var comparisonAdjectiveText = new Text(oneSyllableAdjective);
        var syllablesCountObj = new SyllablesCount(syllablesCount);

        // Act
        var superlativeForm = SuperlativeForm.From(comparisonAdjectiveText, syllablesCountObj);

        // Assert
        superlativeForm.Value.Should().Be(correct);
    }
}
